dist: trusty
language: node_js
node_js:
- 10
before_script:
- npm install
- npm run generate-schema
before_deploy:
- npm run predeploy
deploy:
  skip-cleanup: true
  provider: heroku
  app: kontent-boilerplate-apollo
  api_key:
    secure: '08MPipdSi9JsS7HzUlwrejE2fhPavxZ/oz7n1FHvgdgwVPE2+P7uGTjc1tudwzfwsy6OCULLzjxz95FoeHXrwjtrBRkmBF8zK7fd5fC28bjWRlsm7+RgRhBij2OrvpW/7MxQCoxrUh+hXLrQF47zXOXQykzdgDHKb0XM1EnkU6vF8F59bbUQPIMGlAyJizUntJSH+swaYHd/g4vi1WLE5NGVWV0nwjbTYLZxsi6VxGQ+x079CuMg6SI969rN2eGAEtlLz1u0YEgY/5lt5s+ZPKlpTF8nA0Zqrz29lmhPTIn/10r9Vp+oMtLjMrWdje755viM6hmql29i5KLTJHfRTkvzXZ/N8gh6LZKHyKfmprLWXIE1XOrcKtlzEITS/3nCcKQ/r2HLCvZGCovSN64bbWQy1v73v2OKvpjcrQFmfK9ISwfXMsgtF+j8pOY4p3F3Z/C2q5GUhzWrQxR0ynbZ1N1WRa/4M0xxLD8k1QVwAuNSycEWTMOvWp7C0Y/AQjWG5eRgwxSmS95Du7mthqD93r+Nu9QNplk6OMtlvdCUySpfk8EZtmcRhqJNCQBieWE9rV+KnRfqxJTbLALuCGzmITcF4QsEVUa3/MSdannPIOdHfSo3oGbzKH2y3IrFHze2Vg5P5hQoO+Tn1CjIknMx35WCUofNLlouKy1PkzUuktc='
